Submit data support
fhir-crucible/plan_executor pull request #147
Opened 2019-02-01 19:59 UTC by tstrass

2019-02-06 15:13 UTC, mgramigna requested changes

2019-02-06 15:13 UTC, mgramigna commented on lib/tests/testscripts/scripts/reporting/submit-data.xml
> +				<targetId value="test-Patient-294"/>
The `targetId` does not match the ID of the Patient that's created during `submit-data`. I assume we want these to match up so I'd replace this with the variable `${createPatientId}` that you defined.

2019-02-06 17:30 UTC, mgramigna commented
Other than my small comment, the rest of this looks good to me

2019-02-07 15:20 UTC, mgramigna requested changes
Missing a trailing `}`. 

Also, I'm not seeing anything actually get deleted from the server during teardown. I can easily see this being a problem with the engine and not the testscript itself. Perhaps the teardown portion is never even running in the first place? I doin't see any DELETE requests in the `cqf-ruler` logs. This is probably outside the scope of your PR and we can make a Jira (**EDIT:** Made a Jira for this)

2019-02-07 19:23 UTC, okeefm commented
@tstrass needs a rebase. @mgramigna yeah let's make a Jira task to ensure that setup/teardown methods are run

2019-02-07 19:26 UTC, mgramigna commented
@okeefm Sounds good. I made a Jira

2019-02-07 19:28 UTC, okeefm approved these changes
Looks good pending a rebase and fixing @mgramigna's change requests

2019-02-07 21:47 UTC, mgramigna approved these changes

2019-02-07 21:47 UTC, merged