Fixture id updates for existing TestScripts
fhir-crucible/plan_executor pull request #170
Opened 2019-06-12 17:50 UTC by mgramigna

This PR updates the remaining TestScripts that were not following our new fixture id approach. Such TestScripts are:

* measure-col
    * $collect-data (`brake crucible:execute[<base stu3 url>,stu3,col-collect-data]`)
    * $data-requirements (`brake crucible:execute[<base stu3 url>,stu3,col-data-requirements]`)
    * $submit-data (`brake crucible:execute[<base stu3 url>,stu3,testscript-example-submit-data]`)
    * $evaluate-measure (multiserver) (`brake crucible:execute_multiserver[<base stu3 url1>, <base stu3 url2>,stu3,clinical-reasoning-c21-ccs-individual-multisystem-json]`)
* measure-vte-1-FHIR
    * $data-requirements (`brake crucible:execute[<base stu3 url>,stu3,vte-data-requirements]`)
    * $evaluate-measure (`brake crucible:execute[<base stu3 url>,stu3,vte-evaluate-measure]`)

The rest of the TestScripts either already had this approach implemented, or were made by someone other than us (MRP $data-requirements and $submit-data).

There are a few things that can be tested to verify that the approach is working for all the TestScripts:
* Ensure that all parts of the TestScripts pass
* Ensure that there are no resources with the `MitreTestScript-` id prefix on the server after the TestScript passes
* Ensure that even if we comment out the teardown section, run the test script, uncomment out the teardown section, and run it again, it passes without getting that 409 Conflict error we have seen in the past.

2019-06-14 20:21 UTC, tstrass approved these changes
LGTM besides the egregious mistake I pointed out

2019-06-14 20:21 UTC, tstrass commented on lib/tests/testscripts/scripts/reporting/submit-data.xml
> +        </action>
Botched indentation on this action

2019-06-17 14:06 UTC, mgramigna commented on lib/tests/testscripts/scripts/reporting/submit-data.xml
> +        </action>
Fixed

2019-06-17 14:06 UTC, mgramigna commented on lib/tests/testscripts/scripts/reporting/submit-data.xml
> +        </action>
Fixed

2019-06-20 14:19 UTC, okeefm requested changes
@mgramigna Only comment I found is that the `vte-submit-data` TestScript (not edited in this PR) has one `create` operation in the setup that should be switched to an `update` operation.

2019-06-20 15:29 UTC, mgramigna commented
@okeefm Good catch. Just pushed the update.

2019-06-24 16:53 UTC, okeefm approved these changes
Looks good to me.

2019-06-24 16:55 UTC, merged